### ISSUE TITLE
DEP: Python 3.8 Support

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#1111]
Related to #930

Thinking about pyproj 3.4.x being the last series to support python 3.8.

Community references:

-  Python 3.11 - October 2022 [ref](https://devguide.python.org/versions/). #1110
-  [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html) says numpy drops support for Python 3.8 in April 2023.
- [rioxarray](https://github.com/corteva/rioxarray/issues/582)
- [rasterio](https://github.com/rasterio/rasterio/issues/2773)
- [geocube](https://github.com/corteva/geocube/issues/136)
- [xarray](https://github.com/pydata/xarray/pull/7461)

**Comment by EpicWink** [comment]
Note Python 3.8 is the default Python for Ubuntu 20.04 (Focal), supported by Debian until May 2025. That's quite extended, so that's not my recommendation.

[PEP 569](https://peps.python.org/pep-0569/) says the last security release will be at least October 2024.

My suggestion is for Python 3.8 to be dropped when addressing failing tests in the Python 3.8 CI job becomes too much of a burden, or October 2024, whichever is later.

**Comment by snowman2** [comment]
Stable versions of pyproj for Python 3.8 will continue to be on pypi for those users. Newer releases will have pins in the metadata to ensure disruption does not occur for those using the default python on LTS distributions.

If those users would like to use newer versions of packages in the Python ecosystem, the dead snakes ppa is a great resource: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa. pyproj uses it to test pyproj.

**Comment by snowman2** [comment]
Another thing to consider is that Ubuntu and Python are funded by organizations that provide long term support. pyproj is maintained solely by contributors in their free time. So, the standard for support is a bit different.
