### ISSUE TITLE
Question about transformation to topocentric system

### ISSUE THREAD

**Issue by solarjoe** [pyproj4/pyproj#129]
I would like to transform coordinates (e.g. WGS84 or Bejing1954) to a topocentric system. 

There seem to be several EPSG codes for this (5819, 5820, 5821, 15594, found [here][1] or [here][3]) but none of them is working with PROJ.4 

It just shows the message: `no options found in 'init' file`

I saw that it is possible to define a custom transformation in PROJ using several [parameters][2], but since I am not familiar with this I have no clue how to do it.

Is this possible at all? And i f yes, could someone help me to compile the correct set of parameters?

Just in case someone wants to earn some reputation on gis.stackexchange.com, I also posted the question [there][4].

  [1]: http://georepository.com/crs_5819/EPSG-topocentric-example-A.html
  [2]: http://proj4.org/parameters.html#parameter-list
  [3]: https://epsg.io/15594
  [4]: https://gis.stackexchange.com/questions/268186/how-can-i-transform-coordiantes-to-a-topocentric-system-using-proj-4

**Comment by solarjoe** [comment]
I mean an Scene East-North-Up (ENU) in the page you linked. 

So are the [5825](https://epsg.io/5825) and [5700](https://epsg.io/5700) ENU projections but with different origins?

But I would also have to get a complete set of parameters for each lat/lon, right? Or is this fixed?

**Comment by micahcochran** [comment]
Under that link it tells you that 5825 is defined as:
```+proj=tmerc +lat_0=-35.31773627777778 +lon_0=149.0092948305555 +k=1.000086 +x_0=200000 +y_0=600000 +ellps=aust_SA +towgs84=-117.808,-51.536,137.784,0.303,0.446,0.234,-0.29 +units=m +no_defs```

You can just change the `lat_0` and and `lon_0` to the coordinate of your 0,0, and set `x_0` and `y_0` to `0`.

It will give you a grid that is pretty accurate.  I would suggest using the `etmerc` projection instead, but it is just a little better for a larger area.

5700 uses `utm` zone 1 south, which in the current PROJ.4 is set to `etmerc` algorithm.  The computation of that is [here in PROJ.4](https://github.com/OSGeo/proj.4/blob/ec0fd9c68d24eb18f7352e822329069454892f90/src/proj_etmerc.c#L367) is used to convert from the zone number to set the equivalent to `lon_0`.  It will be somewhat similar to

I don't remember is `lam0` is radians or degrees.

Last point, with either of those projection your Z value should be metres of elevation above sealevel.
c#L367) is used to convert from the zone number to set the equivalent to `lon_0`.  I don't remember is `lam0` is in the units radians or degrees.

Last point, with either of those projection your Z value should be metres of elevation above sealevel, NOT meters above the earth geoid or grid of the terrain.

**Comment by ralphtee** [comment]
Usually, a "topocentric" grid (East-North-Up, ENU) would mean results of EPSG Operation Method No 9836 (or 9837). (Details in the IOGP Publication 373-7-2, Pg 95-99.) The ENU is a *coordinate conversion that is not a map projection*. So, it is more apt to say *"to convert XYZ (ie geocentric coordinates) or LLH (ie geodetic coordinates)"*, rather than *"to transform"* or *"to project"*. My sincerest apology for being a stickler at this because they do mean very different things.

An excerpt from the aforesaid document is as below.

![topocentric](https://user-images.githubusercontent.com/22031088/48659002-ed71ac80-ea85-11e8-8ff4-94ae0dee9c32.png)

* The ENU grid is regularly used in survey engineering to simplify communication at work site, in GNSS baseline processing reports, and in traverse adjustment reports.

* It appears that this method is not yet supported in PROJ 5.2.0 (but hopefully soon) =)

* For avoidance of doubt - do take care to differentiate the many categories of EPSG codes. Eg, there are EPSG codes for measurement units, axis systems, ellipsoids, datums, operation methods, SRS/CRS, and etc.

**Comment by kbevers** [comment]
Thanks @ralphtee! By following the material you have linked to it should be simple for anyone wishing to add this operation to PROJ.

**Comment by snowman2** [comment]
Closing as the issue has been propagated upstream.

**Comment by snowman2** [comment]
https://github.com/OSGeo/PROJ/pull/2444
