### ISSUE TITLE
API: different (duplicated) ways to create a CRS 

### ISSUE THREAD

**Issue by jorisvandenbossche** [pyproj4/pyproj#271]
From discussion in https://github.com/pyproj4/pyproj/pull/263#discussion_r275495702, moving it here.

The ``CRS`` object has multiple ways to be created:

- `CRS(..)`: the actual class constructor, accepts WKT string, a proj.4 string, a proj.4 dictionary, or with proj.4 keyword arguments (and actually also an `'authority:code'` string, which is not documented)
- `CRS.from_epsg(..)`: accepts an integer EPSG number
- `CRS.from_string(..)`: accepts an EPSG, PROJ, or WKT string
- `CRS.from_user_input(..)`: accepts various input, "dispatches to from_epsg, from_proj, or from_string" according to its documentation. And also accepts objects that have a `to_wkt` method.

So in the other PR, I was wondering if this `__init__` is actually needed? (I mean the user facing functionality part of it). Because now that means that you can do both `CRS("..some string..")` as `CRS.from_string("..some string..")` ? Which means we give users two ways to do exactly the same, I would be fine to only have the `from_..` methods as the user facing way to create a CRS object.

Another observation now I am writing this: there was the idea at one point to have a `from_proj` method? (if we keep the different `from_..` methods, that seems nice to have as well)

I think it would be nice to make a choice ourselves. What is the point of having a `CRS.from_user_input(..)` for the user if `CRS(..)` gives you exactly the same? (or the other way around)

**Comment by snowman2** [comment]
I will need time to think on this one.

**Comment by snowman2** [comment]
Okay, so I haven't made any decisions on this yet, but I figured a brain dump here might help me think though things and also give you more insight into what I am thinking at the same time.

The design for the `pyproj.CRS` initialization was a combination of the `rasterio.CRS` and `Proj` style initializations.

The `__init__` method on the CRS class is nice to have. It goes along with the `Geod` and `Proj` classes initalization methods. My current preference would be to allow the `from_user_input` style in the `__init__` method and just let the user throw whatever they want at it. But, `from_user_input` it does not support all initialization methods such as `from_auth` or `from_cf` (probably could add support for that if we wanted to).

The reasoning for having the current initialization options is for a couple of reasons:

1. To allow the CRS initialization methods be in alignment with the `rasterio.CRS` and likely the future `fiona.CRS` classes. This way, the user can easily switch between using `rasterio.CRS`, `fiona.CRS`, or `pyproj.CRS` in their code bases without much change necessary.
2. It is nice to break out the code for each initialization method into its own method. And since it is there, let the user use it as well if they so choose.

**Comment by snowman2** [comment]
Currently rasterio supports initialization from the `__init__` with proj mappings:
https://github.com/mapbox/rasterio/blob/c2a495d536db6328e018cb65ce7cc0b8c559a937/rasterio/crs.py#L46

My preference is to leave all initialization methods as it allows for interoperability between CRS classes as I believe the `fiona.CRS` class will be similar to the `rasterio.CRS` class.

Thoughts? Opinions?

**Comment by jorisvandenbossche** [comment]
Sorry for the slow reply here. 
Putting some more random thoughts here:

I was also looking that the from/to methods consistency. Currently we have

- `to_cf` and `from_cf`
- `to_epsg` and `from_epsg`

and

- `to_proj4`
- `to_proj4_dict`
- `to_wkt`

and 

- `from_string`
- `from_user_input`
- `from_auth`

So given the above, we might also want to have `from_wkt` and `from_proj4`? (rasterio has both) And maybe `from_proj4_dict`.

But then I was thinking, what's the difference between `from_string` and `from_user_input` ?

**Comment by jorisvandenbossche** [comment]
> My preference is to leave all initialization methods as it allows for interoperability between CRS classes as I believe the fiona.CRS class will be similar to the rasterio.CRS class.

But I don't think it currently does allow for interoperability? 
Eg passing a rasterio.CRS class to pyproj.CRS(..) will fail, I think? And the other way around as well.

It is currently the `from_user_input` method that checks for a `to_wkt` method and in this way does give some interoperability.

**Comment by snowman2** [comment]
Also, probably want a `to_auth` method.

**Comment by snowman2** [comment]
Your points about from_wkt or from_proj or from_dict missing definitely poke holes in my argument :-). Well, I think that rethinking the CRS class initialization strategy is warranted

**Comment by jorisvandenbossche** [comment]
> Also, probably want a to_auth method.

For this one, I would say: practically beats purity, nobody will need that if you already have `to_epsg` (because if you *build* a CRS from authority, it is already in its name / `srs`)

> Well, I think that rethinking the CRS class initialization strategy is warranted

To be clear, I am not *necessarily* saying that we should remove all accepted values from `CRS(..)` itself, I am also not yet convinced of what would be best. It only seems that it currently is somewhat arbitrary (at least from a user perspective) what is accepted and what not.

From a code perspective, it could also make sense to accept in `CRS(...)` whathever `proj_create(..)` accepts directly (so basically like the current `from_string`, I think)

**Comment by snowman2** [comment]
The thinking behind the `to_auth` would be for times when the CRS was initialized from a WKT string. It would be nice to identify the authority. But, I guess you would need the authority name or a known list to iterate over. This would be useful in the repr.

**Comment by snowman2** [comment]
I think reorganizing the initialization of the CRS class code would be a good thing to increase clarity. I have some ideas, but will need to turn them into code and tinker a bit and come back to this issue.

**Comment by snowman2** [comment]
> we might also want to have from_wkt and from_proj4

I guess one could argue that `from_string` is not really necessary at all. If we have `from_user_input`, then `from_string` is not needed and neither is `from_wkt` or `from_proj4`.

**Comment by snowman2** [comment]
On possible reorganization in #307

**Comment by snowman2** [comment]
After sleeping on it, I think having more methods like the `rasterio.CRS` is better. It just makes interoperability much nicer and it makes transitioning back and forth as simple as changing an import.

So, instead of removing, adding would be the way to go.

Next steps I am thinking about:

Add:
- `from_wkt`
- `from_proj4`
- `from_dict`
Rename:
- `to_proj4_dict` to `to_dict`

Not sure about adding a `to_string` method though. I almost would just return `srs` in that case. But, I guess you could use `to_authority` and convert to string first and if it fails use `srs` (take the code from the repr and put it in a method).

**Comment by snowman2** [comment]
I merged in #307, because I liked the changes and it had some important fixes in it. However, it doesn't mean it is the final version before release. If you have time to try it out and let me know what you think, I would appreciate it @jorisvandenbossche.

**Comment by jorisvandenbossche** [comment]
Yeah, sorry for the delay here. I added some comments now. Mainly about the main `__init__` I have some differing opinion. 
In light of what you actually proposed in #309 (a clearer direct interface to `proj_create`), my suggestion would be that we can perfectly have that in the python CRS class: let the `__init__` be a basically direct interface to `proj_create`, and then we have all the `from_..` methods that preprocess and convert the user input to something that `proj_create` can handle, as we already have now.

**Comment by jorisvandenbossche** [comment]
> Rename to_proj4_dict to to_dict

Was there a rationale for this one? I personally like `to_proj4_dict`, as it is much more explicit 
(in general we should discourage users to use proj4 representations, so also for that reason having it in the name is clearer)

**Comment by snowman2** [comment]
So, I think the answer for the direction to go on `__init__` and `to_proj4_dict` depends on how closely `pyproj.CRS` should mirror `rasterio.CRS`.

I definitely agree with what you have said like idea of making the `__init__` string based without any filters. I hesitate only because of the current `rasterio.CRS` class implementation of `__init__` and the `to_dict` method that already exists.

**Comment by jorisvandenbossche** [comment]
Note that `rasterio.CRS` actually does not have such a flexible `__init__`. There, it only supports a dictionary of proj4 params, and it has all the other `from_..` methods for other ways of instantiation. 
Mirroring rasterio exactly here is something I would personally not do, given that with the new proj 6, we want to demote the importance of proj4 strings/dicts, and thus not give it as the only argument for the main init. 
So since we are already deviating from rasterio *for the main init* function, I think we can just try to make a best possible design for pyproj itself (of course, this is very subjective .. :-)). Having somewhat consistency for the other `from_..`/`to_..` methods with rasterio is certainly a good goal.

Still accepting the kwargs/dict for consistency with pyproj.Proj is a good argument. Looking at it from a new user point of view, it is still not fully clear to me what the usecase of pyproj.Proj is, though. 

Since sometimes it is easier to show with code what you mean, a quick idea here: https://github.com/pyproj4/pyproj/commit/ac9b10af3395339c127a9dfeb21fdfbbd6924e88 (didn't actually test it, so there will probably be errors in it)

**Comment by snowman2** [comment]
I currently think of the initialization of the `rasterio.CRS` and `pyproj.Proj` classes as the baseline functionality desired for the `pyproj.CRS`. Definitely don't want to restrict ourselves to an exact mirror (otherwise we have much of the existing additions that would need to be thrown out :stuck_out_tongue:). But, if there was a user of one of those classes who had input that originally worked in one of those classes and they wanted to try using it with the `pyproj.CRS` class in its place, it would be nice if it *JustWorked* and also had a few additional useful features.

> we want to demote the importance of proj4 strings/dicts, and thus not give it as the only argument for the main init.

I definitely agree that PROJ strings/dicts should not be the only argument in the intitialization and am fully supportive of more than just that. Also, I don't think we need to demote the usage of PROJ strings/dicts as input as much as make it clear that if you didn't start with one, it is a bad idea to convert to one as information can be lost (one reason why I didn't originally have a `to_dict`` method). In that vein, adding warnings to the docstrings of `to_dict` and `to_proj4` would be a good idea.

> it is still not fully clear to me what the usecase of pyproj.Proj is

It is an essential class used for transformations in pyproj 1.9.6 and is there at the very least for backwards compatibility. I think most use cases could simply switch to the `pyproj.CRS` class instead. So, having its `__init__` behavior the same as `pyproj.Proj` would be a good idea I think.

**Comment by snowman2** [comment]
I like the change in the names of the preparation functions in: https://github.com/pyproj4/pyproj/commit/ac9b10af3395339c127a9dfeb21fdfbbd6924e88 :+1:

**Comment by snowman2** [comment]
Okay, so after some thought on this, I think the "duplicated" part is finally dawning on me.

So, the holes in my thinking are:
1. I don't personally use the `__init__` from rasterio and just use the to/from methods (mostly `from_user_input`). And having the to/from methods provide interoperability.
2. If transitioning from Proj to use CRS, have to make changes anyway, so not a big deal if the `__init__` is different.
3. I like the simplicity and reduced overhead of the `__init__` in #309. So, maybe no `__init__` is needed for the `pyproj.CRS` and just use the base class `__init__`?
4. ....

Anyway, @jorisvandenbossche, if you would like to make a PR based on https://github.com/pyproj4/pyproj/commit/ac9b10af3395339c127a9dfeb21fdfbbd6924e88, I would be open to it.

**Comment by snowman2** [comment]
Thanks for the recommendations! Definitely helped to improve the interface. I am going to close this due to inactivity. But, feel free to reopen if you would like to continue the discussion.
