### ISSUE TITLE
Check if is_bound for to_authority?

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#317]
https://github.com/OSGeo/gdal/blob/60ab2831abf9446c629b3a417a16cb35e7f41e63/gdal/ogr/ogrspatialreference.cpp#L7376-L7391

**Comment by snowman2** [comment]
Current behavior:
```
>>> from pyproj import CRS
>>> ccs = CRS("+init=epsg:4328 +towgs84=0,0,0")
>>> ccs.to_authority()
>>> ccs.to_authority(min_confidence=0)
>>> ccs.source_crs.to_authority()
('EPSG', '4978')
```

**Comment by snowman2** [comment]
Do we actually want to force this to get the authority from the source CRS like GDAL? 
It does loose the towgs84 parameters and we use this in to_string, so I am not entirely sure how I feel about this one. I am leaning towards no.

**Comment by snowman2** [comment]
```
>>> from pyproj import CRS
>>> CRS("+init=epsg:4328 +towgs84=0,0,0") == CRS("+init=epsg:4328")
False

```

**Comment by jorisvandenbossche** [comment]
The Bound CRS once you have a towgs84 clause is something *very* confusing, but I agree we should probably follow proj here and not GDAL, as otherwise the roundtrip to authority is not fully correct. 
But we might need to better document this case.

Another thought: we could also raise a warning when you try to do `to_epsg` or `to_authority` and have a BoundCRS (as I don't think any bound crs will ever give a result), explaining to the user they have a bound crs and how to get the actual crs. 
(although, the `to_epsg` is also used internally, and then we certainly don't want warnings ..)

**Comment by snowman2** [comment]
I added more info in the docstrings with an example for a bound CRS. Thanks for the suggestion 👍
