### ISSUE TITLE
Help library maintainers to support pyproj < 2 and  > 2

### ISSUE THREAD

**Issue by fmaussion** [pyproj4/pyproj#423]
Folks, I know you are doing heavy, future oriented work on getting pyproj future proof. But still, I have to complain a bit.

The pyproj updates have been the main maintenance burden of an otherwise low-key, low-maintenance API I'm maintaining ([salem](https://github.com/fmaussion/salem)). As of now, I am confused about how to proceed. I hope my questions are not too simple, but my current bandwith to get into the depths of pyproj is limited...

1. pyproj.Proj has disappeared from the docs, but is not formally deprecated. Is pyproj.CRS a drop in replacement and, more importantly, does it work in pyproj previous to 2.0 ?

2. What do I do with the `'+init=<authority>:<code>' syntax is deprecated` cycle? Salem opens shapefiles and creates a proj out of it. Shapefiles read with geopandas frequently come with a dict attached to them (e.g. `{'init': 'epsg:4326'}`). I don't think it should be salem's role to clean up these CRS -> can pyproj expose utilites to help clean those crs strings / dict that still work with pre- and post- pyproj 2.0? My current take is that I'm just going to silence these warnings, which is certainly not future proof...

**Comment by snowman2** [comment]
1. https://pyproj4.github.io/pyproj/stable/api/proj.html. It's not going away any time soon. However, with the addition of the `always_xy` option in transformations, you will likely have to change what you do based on the version of pyproj.

2/ Geopandas is working on it: https://github.com/geopandas/geopandas/issues/1003. I would recommend just reading in the `cra_wkt` from Fiona as it is more likely to accurately represent the CRS.

The changes in pyproj are due to the changes in PROJ (https://gdalbarn.com/). They have made many internal changes and pyproj has updated to match those changes. Once PROJ stabilizes, pyproj will likely follow suit.

**Comment by snowman2** [comment]
Also, see: https://github.com/corteva/rioxarray/pull/34/files:
```python
def _get_proj_transformer(src_crs, dst_crs):
    """
    Get pyproj Transformer based on version of pyproj
    Parameters
    ----------
    src_crs: input to create source pyproj.CRS/pyproj.Proj
    src_crs: input to create destination pyproj.CRS/pyproj.Proj
    Returns
    -------
    pyproj Transformer
    """
    if _PYPROJ22:
        return pyproj.Transformer.from_crs(src_crs, dst_crs, always_xy=True).transform

    def ensure_proj(in_crs):
        if not isinstance(in_crs, pyproj.Proj):
            if hasattr(in_crs, "to_dict"):
                in_crs = in_crs.to_dict()
            in_crs = pyproj.Proj(in_crs, preserve_units=True)
        return in_crs

    return partial(pyproj.transform, ensure_proj(src_crs), ensure_proj(dst_crs))
```
