### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#460]
Expected release: Monday, 2019-10-21

https://www.python.org/dev/peps/pep-0569/#schedule

- [x] Update CI/CD (#469)
- [x] Update wheels (https://github.com/pyproj4/pyproj-wheels/pull/18)

Notes:
- Wheels not available for Python 3.8 with linux i686 platform or for OSX a this time.
- Not available on conda-forge yet. Tracking issue: https://github.com/conda-forge/python-feedstock/pull/274

**Comment by zbruick** [comment]
Tried testing MetPy against 3.8 with a testing dependency against pyproj. It failed with a `Proj executable not found. Please set PROJ_DIR variable.` error in Travis. The same config passes with 3.6 and 3.7. You can see the Travis build [here](https://travis-ci.org/Unidata/MetPy/jobs/599800004). I assume this error is because wheels haven't been updated yet.

**Comment by snowman2** [comment]
> I assume this error is because wheels haven't been updated yet.

That is correct. We don't have any Python 3.8 wheels built at this time.
