### ISSUE TITLE
transformer.from_crs flips X and Y in output when transforming

### ISSUE THREAD

**Issue by prinsniels** [pyproj4/pyproj#510]
**Issue**:
When creating a transformer via transformer.from_proj and calling transform on a coordinate set, I expect the same result as calling transform via a transformer created by transformer.from_crs. This does not hold. When creating a transformer via .from_crs the X and Y are switched. See code below.

**using**:
python 3.7
pyproj 2.4.2.post1

**Code**:
```python
print(__version__)
RDX = 103392.0
RDY = 468608.6
p1 = 'epsg:28992'
p2 = 'epsg:4326'
t_proj = Transformer.from_proj(proj_from=Proj(init=p1), proj_to=Proj(init=p2))
t_crs = Transformer.from_crs(crs_from=p1, crs_to=p2)
print(f"FROM_PROJ => {t_proj.transform(xx=RDX, yy=RDY)}")
print(f"FROM_CRS => {t_crs.transform(xx=RDX, yy=RDY)}")
coords_proj = t_proj.transform(xx=RDX, yy=RDY)
coords_crs = t_crs.transform(xx=RDX, yy=RDY)
print("Equal",  coords_crs == coords_proj)
print("Flipped", coords_crs[0] == coords_proj[1] and coords_crs[1] == coords_proj[0])
```

**Result**:
2.4.2.post1
FROM_PROJ => (4.632256139162482, 52.20316882027802)
FROM_CRS => (52.20316882027802, 4.632256139162482)
Equal False
Flipped True

I tried this for multiple epsg codes, all show the same result.

**Comment by jorisvandenbossche** [comment]
@prinsniels this is expected behavior, and has to do with recent changes in PROJ to correctly follow the axis order of EPSG codes and the deprecated "init=.." syntax.

You should normally also see a deprecation warning when creating the Proj using `init` (at least with the latest version of pyproj):

```
In [5]: t_proj = Transformer.from_proj(proj_from=Proj(init=p1), proj_to=Proj(init=p2)) 
/home/joris/scipy/repos/pyproj/pyproj/crs.py:79: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))
/home/joris/scipy/repos/pyproj/pyproj/crs.py:79: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))
```

and when using this preferred method, you will see that both methods return the same:

```
In [6]: t_proj_new = Transformer.from_proj(proj_from=Proj(p1), proj_to=Proj(p2))  

In [7]: t_crs = Transformer.from_crs(crs_from=p1, crs_to=p2) 

In [8]: print(f"FROM_PROJ => {t_proj_new.transform(xx=RDX, yy=RDY)}") 
   ...: print(f"FROM_CRS => {t_crs.transform(xx=RDX, yy=RDY)}") 
FROM_PROJ => (52.20316882027802, 4.632256139162482)
FROM_CRS => (52.20316882027802, 4.632256139162482)
```

Now it both gives the "flipped" behaviour, if you want to keep the lon/lat order, you can specify the `always_xy` option:

```
In [9]: t_crs2 = Transformer.from_crs(crs_from=p1, crs_to=p2, always_xy=True) 

In [10]: print(f"FROM_CRS => {t_crs2.transform(xx=RDX, yy=RDY)}")  
FROM_CRS => (4.632256139162482, 52.20316882027802)
```

See the docs for more details on this and the background rationale: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6 (the links at that section)

**Comment by prinsniels** [comment]
Thnxs for the quick reply! I was not aware of that. Fixed it on my side. please close the issue
