### ISSUE TITLE
Python 3.7 intermittent core-dump

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#651]
Strangely only happens with Python 3.7

First appearance: https://travis-ci.com/github/pyproj4/pyproj/jobs/341216820 (1 day ago)
Success: https://travis-ci.com/github/pyproj4/pyproj/jobs/341643706
Fail: https://travis-ci.com/github/pyproj4/pyproj/jobs/341644980

- `pyproj` issue?
- `PROJ` issue?

**Comment by snowman2** [comment]
It was discovered due to changes in #649 as tests passes in CICD when skipping the test.

I was unable to reproduce locally, so not entirely sure what is going on. Pinning to 3.7.2+ removed the core dumping. Not sure why, but it works.

**Comment by TimoRoth** [comment]
Could this be the same issue we are having since a long while now?

Looks like this: https://github.com/OGGM/OGGM-Anaconda/runs/793408792?check_suite_focus=true#step:4:756
OSX gives a little bit more error output as linux, showing the assertion that triggered the segfault.

It has been seemingly randomly appearing and then going away, I have never been able to make much sense out of it. Given the odd backtrace purely going through pytest code leaves me even more puzzled.
