### ISSUE TITLE
PROJ_NETWORK: First transform fails, succeeds afterwards

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#705]
https://gis.stackexchange.com/questions/373550/first-call-to-transform-fails-with-inf-all-subsequent-calls-are-ok-what-cou

Worth looking into later.

**Comment by snowman2** [comment]
Unable to re-produce in the latest version. Removed the local cache and still not able to re-produce.

**Comment by cipri-tom** [comment]
@snowman2 this is happening for me on MacOS. I have reached here [from geopandas `.to_crs()`](https://github.com/geopandas/geopandas/issues/1972).

Seeing your suggestion on the linked GIS question, I am able to consistently make get it to fail for the first call to `transform`, and fix it by `pyproj.network.set_network_enabled(False)`. 

I have installed from conda-forge on MacOS 10.15.7 (please see linked issue for environment file).

I believe the problem may be caused by some incorrect CA on my machine -- this is an enterprise laptop and they have overriden some of the certificates. I am not sure how to use `set_ca_bundle_path()` to check if using the correct ones would work.

If this is the case, may I suggest a harder error / warning, rather than just returning `inf` upon failure ?

Thanks,
Ciprian

**Comment by snowman2** [comment]
> may I suggest a harder error / warning, rather than just returning inf upon failure ?

There is a `errcheck=True` flag you can turn on.

**Comment by snowman2** [comment]
Also, you can pre-download the grids: https://pyproj4.github.io/pyproj/stable/transformation_grids.html

**Comment by cipri-tom** [comment]
Thanks for the fast reply ! 

>There is a errcheck=True flag you can turn on.

Which method has the `errcheck=True` flag ? I don't see it on `Transformer.from_crs()`.

Sorry, I am a second-hand user, haven't interacted with pyproj directly, only through geopandas. They've suggested to try this code to check if the problem comes from here:

```python
from pyproj import CRS, Transformer
from shapely.ops import transform

origin = CRS.from_user_input(df.crs)
target = CRS.from_user_input('+proj=lcc +lat_1=33 +lat_2=45 +lat_0=39 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs')

transformer = Transformer.from_crs(origin, target, always_xy=True)

geom = df.geometry.iloc[2]  # shapely.geometry causing a problem

transform(transformer.transform, geom).wkt
```

> Also, you can pre-download the grids

Thanks ! It seems to work with disabling the network, as well. Since I've never downloaded the grids, am I losing in accuracy if I disable network ?

**Comment by snowman2** [comment]
> Which method has the errcheck=True flag ? I don't see it on Transformer.from_crs().

The `transform` method [ref](https://pyproj4.github.io/pyproj/stable/api/transformer.html#pyproj.transformer.Transformer.transform)

> Since I've never downloaded the grids, am I losing in accuracy if I disable network ?

That is a possibility. It depends on the transformation.

**Comment by snowman2** [comment]
Related: https://github.com/pyproj4/pyproj/discussions/1454

**Comment by snowman2** [comment]
@rouault, I am adding you to this issue so you are aware. I haven't had time to dig into it yet, but thought that the frequency of reports was worth bringing it to your attention.

**Comment by snowman2** [comment]
https://github.com/OSGeo/PROJ/pull/4302
