### ISSUE TITLE
Installing on Windows 10

### ISSUE THREAD

**Issue by Readdeo** [pyproj4/pyproj#90]
Hi!
I tried  to install it with pip install... and with the setup.py. I installed the vc++ package, but after that, i get this error:     _proj.c(240) : fatal error C1083: Cannot open include file: 'geodesic.h': No such file or directory
I found GeographicLib-1.46, but i have no idea how to install it. Can you please help me with that?

**Comment by micahcochran** [comment]
pyproj version 1.9.5.1 includes PROJ.4 in the "src" folder, which also includes GeographicLib.

Under Windows, your [Visual C++ compiler version has to be the same version that was used to compile that version of Python](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F).

What version of Python are you using and what Visual C++ did you install?

**Comment by Readdeo** [comment]
Python 2.7.12
and
C++ compile package for python 2.7 is 9.0.1.30729

**Comment by micahcochran** [comment]
I've had success using [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266). 

Please provide more of the error message from the command `C:\..> pip install pyproj` , it could prove helpful.

**Comment by Readdeo** [comment]
This is what i see: blob:https%3A//snag.gy/410fa00c-5a3d-4005-8782-c18581d9692f

**Comment by micahcochran** [comment]
That screenshot was helpful.   It looks like you have set the PROJ_DIR environment set to an existing installation of the PROJ.4 library.  PROJ.4 version 4.9.0 or greater is required.

In order to use your existing PROJ.4 installed, you will also need to have the headers install. If that is a different location from PROJ_DIR under the "include" subdirectory, you can use the PROJ_INCDIR environment variable to point to the header files.  (PROJ_INCDIR has not been documented.)   There is a PROJ_LIBDIR to point to a path that the library file is located.  Otherwise, the default library directory is PROJ_DIR under the "lib" or "lib64" subdirectory.

Alternatively, pyproj includes the source code for PROJ.4 version after 4.9.2 (copy of late 2015 from github repo),  which pip will install.

**Comment by snowman2** [comment]
Refer to #216
