### ISSUE TITLE
[BUG] pyproj.datadir not correct with conda

### ISSUE THREAD

**Issue by KhanMechAI** [pyproj4/pyproj#999]
Using pyproj version 3.2.1
conda version 4.9.2
geopandas version 0.9.0

When intialising a geopandas GeoDataFrame I started running into the invalid projection error. Followed the debug steps and ran:

`python
pyproj.datadir.get_data_dir()
`
yielding:
`
<rest_of_path>\envs\<myenv>\lib\site-packages\pyproj\proj_dir\share\proj
`
But this has a typo in it,  `conda` creates `...envs\<your_env>\Lib\...`, capital **L** not lower case **l**.

p.s. I'm from Australia, we spell in initialise with an 's', not 'z'

**Comment by snowman2** [comment]
I believe you installed pyproj using pip inside of a conda environment, correct?

**Comment by snowman2** [comment]
When using conda, I recommend:
1. Install the packages in a new conda environment (https://conda-forge.org/docs/user/tipsandtricks.html : "we recommend always installing your packages inside a new environment instead of the base environment from anaconda/miniconda. Using envs make it easier to debug problems with packages and ensure the stability of your root env.")
2. Use the conda-forge channel (be mindful of channel priority: https://conda-forge.org/docs/user/tipsandtricks.html)
3. Make sure you activate your conda environment
4. Don't `pip install` into a conda environment

https://pyproj4.github.io/pyproj/stable/installation.html
```
conda config --prepend channels conda-forge
conda config --set channel_priority strict
conda create -n env numpy rasterio geopandas matplotlib descartes
conda activate env
```

> How do I set in the conda created virtual environment the system's libraries for GEOS?

If you want to use the system libraries, I don't recommend using conda. Conda includes the libraries in that environment.

**Comment by Philipp-Otter** [comment]
Hello everyone,

i run into a similar issue. I just created a new environment and installed all packages (geopandas, pyrosm, cykhash=1.0.2, jupyterlab, pyyaml) from conda forge (conda install -c conda-forge). 
The first error I get is:
 anaconda3\envs\P4B_Py_3.9\lib\site-packages\pyproj\__init__.py:89: UserWarning: pyproj unable to set database path.
  _pyproj_global_context_initialize(), but that one can be fixed by capitalizing Lib as recommended by KhanMechAI. 
Now I get the error:
anaconda3\envs\P4B_Py_3.9\lib\site-packages\pyproj\datadir.py:38: UserWarning: pyproj unable to set database path.
  _global_context_set_data_dir()
seems like a similar issue

**Comment by snowman2** [comment]
If you followed all of these steps (https://github.com/pyproj4/pyproj/issues/999#issuecomment-971575881) and are still having issues, then I recommend making an issue here: https://github.com/conda-forge/pyproj-feedstock/

**Comment by snowman2** [comment]
Though this path `<rest_of_path>\envs\<myenv>\lib\site-packages\pyproj\proj_dir\share\proj` tells me that `pip install ` was used.

**Comment by Philipp-Otter** [comment]
yea true.
i guess its due to pyrosm, which pip installs pyproj when you conda forge install pyrosm. i will try to install pyproj first and update you.
thanks for your help

**Comment by Philipp-Otter** [comment]
![image](https://user-images.githubusercontent.com/91256148/142254068-ae7d83c9-93dc-4027-a24c-637ac14fca91.png)

Just to let you know, I rebuild the environment with only conda forge, but the code still does not work. I guess it is due to the message on the screenshot. i will create an issue in the other repo.

thanks again for your help

**Comment by jorisvandenbossche** [comment]
@Philipp-Otter looking at that message, that might also have been some download or unpacking issue. Could you maybe try again? 

> i guess its due to pyrosm, which pip installs pyproj when you conda forge install pyrosm.

That would be strange. Checking the pyrosm recipe, it lists geopandas as a dependency, which in turn depends on pyproj. If you install pyrosm with conda, pyproj should also be coming from conda (unless you eg already installed it before)

---

In general, although I also don't recommend using pip to install things in a conda environment myself (especially for non-pure python packages), it should still work if you don't swap back and forth between pip and conda. For example, to test, I created a conda environment installing base python and pip etc with conda, activated it, and then installed pyproj with pip, and that works fine. 
The fact that there might be some issue with capital or lower case `Lib` is strange, as pyproj doesn't hardcode such paths, but gets it from the path where pyproj is installed.

**Comment by Philipp-Otter** [comment]
Hello @jorisvandenbossche,

i think my whole anaconda installation was corrupted, so i decided to uninstall everything and start again from scratch. Now everything works fine.

thanks everyone

**Comment by snowman2** [comment]
Glad to hear that you got it working 👍. @KhanMechAI, I am assuming that the discussion should help resolve your issue as well. If not, please ask another question.
